### ISSUE TITLE
New version out (v1.3.0) but bot can't find due to missing `v`

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/gpflow-feedstock#1]
It seems the new version numbers have a `v` out in front. This is causing the bot not to find the tarball properly. Please update the recipe when you get a chance.

**Comment by jschueller** [comment]
I tried to fix this, but then i've got a cryptic error message:
https://travis-ci.org/conda-forge/gpflow-feedstock/builds/450731960?utm_source=github_status&utm_medium=notification
