### ISSUE TITLE
Is this still mantained?

### ISSUE THREAD

**Issue by Sclafus** [conda-forge/gpflow-feedstock#22]
### Comment:

Good morning,
It looks like that this package has not been updated for some time, even if the upstream is still lively.
Is this still maintained?

**Comment by Sclafus** [comment]
@cxhernandez tagging you since you are appointed as the maintainer of this package in the readme

**Comment by jakirkham** [comment]
This was just updated with a new maintainer in PR: https://github.com/conda-forge/gpflow-feedstock/pull/24

Closing
