### ISSUE TITLE
Release latest version of gpflow in conda-forge?

### ISSUE THREAD

**Issue by westinhuang** [conda-forge/gpflow-feedstock#23]
### Comment:

@cxhernandez From README, you are only one maintainer of this repo. Do you have plan to release latest version?

**Comment by westinhuang** [comment]
@conda-forge-admin, please add user @westinhuang

**Comment by jakirkham** [comment]
This has been updated to a newer version with your PR: https://github.com/conda-forge/gpflow-feedstock/pull/24

Though admittedly this is still behind a few versions. Looks like we need to add a few dependencies to conda-forge to get this more up-to-date

Let's work through that process and see if we can get this to a more recent version

**Comment by westinhuang** [comment]
@jakirkham Thank you!

**Comment by jakirkham** [comment]
No thank you Westin! 🙏

**Comment by westinhuang** [comment]
@jakirkham Do you know why latest version in conda-forge is still 2.5.2, not our 2.6.4?

**Comment by jakirkham** [comment]
Because apparently CI did not run when it was merged into `main`. Not sure why 😕

Have [manually started it]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=963007&view=results ). Hopefully that clears it up

Let's keep an eye on CI in case this reoccurs

**Comment by westinhuang** [comment]
@jakirkham I finish latest version push. Thank you again!

**Comment by jakirkham** [comment]
Great thanks Westin! 🙏
